### ISSUE TITLE
Crash on start

### ISSUE THREAD

**Issue by ksga** [xbmc-danish-addons/plugin.video.drnu#80]
Hi. Love this add-on, so really sad that it started crashing a couple of weeks ago. Didn't update anything else (maybe some add-on did so in the background), so seems a bit strange.

Running OSMC, but till now it's been playing nice.

Enabled debug logging, and the output when trying to load the add-on:
`2023-01-25 20:06:55.041 T:613     DEBUG <general>: PushCecKeypress - received key  b duration 0                                                                                     2023-01-25 20:06:55.059 T:557     DEBUG <general>: HandleKey: 11 (0x0b, obc244) pressed, action is Select                                                                           2023-01-25 20:06:55.060 T:557     DEBUG <general>: CGUIMediaWindow::GetDirectory (plugin://plugin.video.drnu/)
2023-01-25 20:06:55.060 T:557     DEBUG <general>:   ParentPath = [addons://sources/video]2023-01-25 20:06:55.060 T:919     DEBUG <general>: Thread JobWorker start, auto delete: true                                                                                        2023-01-25 20:06:55.061 T:920     DEBUG <general>: Thread waiting start, auto delete: false                                                                                         2023-01-25 20:06:55.069 T:919     DEBUG <general>: CAddonDatabase::SetLastUsed[plugin.video.drnu] took 9 ms                                                                         2023-01-25 20:06:55.070 T:921     DEBUG <general>: Thread JobWorker start, auto delete: true                                                                                        2023-01-25 20:06:55.070 T:920     DEBUG <general>: StartScript - calling plugin DR TV('plugin://plugin.video.drnu/','6','','resume:false')                                          2023-01-25 20:06:55.070 T:922     DEBUG <general>: Thread LanguageInvoker start, auto delete: false                                                                                 2023-01-25 20:06:55.070 T:922      INFO <general>: initializing python engine.            2023-01-25 20:06:55.070 T:922     DEBUG <general>: CPythonInvoker(20, /home/osmc/.kodi/addons/plugin.video.drnu/default.py): start processing                                       2023-01-25 20:06:55.161 T:557     DEBUG <general>: ------ Window Init (DialogBusy.xml) ------                                                                                       2023-01-25 20:06:55.168 T:613     DEBUG <general>: PushCecKeypress - received key  b duration 127                                                                                   2023-01-25 20:06:55.252 T:922     DEBUG <general>: -->Python Interpreter Initialized<--
2023-01-25 20:06:55.252 T:922     DEBUG <general>:                                        
2023-01-25 20:06:55.253 T:922     DEBUG <general>: CPythonInvoker(20, /home/osmc/.kodi/addons/plugin.video.drnu/default.py): the source file to load is "/home/osmc/.kodi/addons/plugin.video.drnu/default.py"                                                                2023-01-25 20:06:55.253 T:922     DEBUG <general>: CPythonInvoker(20, /home/osmc/.kodi/addons/plugin.video.drnu/default.py): setting the Python path to /home/osmc/.kodi/addons/plugin.video.drnu:/home/osmc/.kodi/addons/script.module.certifi/lib:/home/osmc/.kodi/addons/script.module.chardet/lib:/home/osmc/.kodi/addons/script.module.dateutil/lib:/home/osmc/.kodi/addons/script.module.idna/lib:/home/osmc/.kodi/addons/script.module.inputstreamhelper/lib:/home/osmc/.kodi/addons/script.module.requests-cache/lib:/home/osmc/.kodi/addons/script.module.requests/lib:/home/osmc/.kodi/addons/script.module.six/lib:/home/osmc/.kodi/addons/script.module.urllib3/lib:/usr/lib/python39.zip:/usr/lib/python3.9:/usr/lib/python3.9/lib-dynload:/usr/local/lib/python3.9/dist-packages:/usr/lib/python3/dist-packages
2023-01-25 20:06:55.253 T:922     DEBUG <general>: CPythonInvoker(20, /home/osmc/.kodi/addons/plugin.video.drnu/default.py): entering source directory /home/osmc/.kodi/addons/plugin.video.drnu
2023-01-25 20:06:55.253 T:922     DEBUG <general>: CPythonInvoker(20, /home/osmc/.kodi/addons/plugin.video.drnu/default.py): instantiating addon using automatically obtained id of "plugin.video.drnu" dependent on version 3.0.0 of the xbmc.python api
2023-01-25 20:06:56.800 T:922     DEBUG <CAddonSettings[plugin.video.drnu]>: trying to load setting definitions from old format...
2023-01-25 20:06:56.800 T:922     DEBUG <CSettingsManager>: requested setting (fanart.size) was not found.
2023-01-25 20:06:56.805 T:922     ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'json.decoder.JSONDecodeError'>
                                                   Error Contents: Extra data: line 1 column 2523 (char 2522)
                                                   Traceback (most recent call last):
                                                     File "/home/osmc/.kodi/addons/plugin.video.drnu/default.py", line 7, in <module>
                                                       handle = addon.DrDkTvAddon(plugin_url=sys.argv[0], plugin_handle=int(sys.argv[1]))
                                                     File "/home/osmc/.kodi/addons/plugin.video.drnu/resources/lib/addon.py", line 73, in __init__
                                                       self.api = tvapi.Api(self.cache_path, tr, get_setting)
                                                     File "/home/osmc/.kodi/addons/plugin.video.drnu/resources/lib/tvapi.py", line 48, in __init__
                                                       self.refresh_tokens()
                                                     File "/home/osmc/.kodi/addons/plugin.video.drnu/resources/lib/tvapi.py", line 101, in refresh_tokens
                                                       self.read_token(self.token_file.read_bytes())
                                                     File "/home/osmc/.kodi/addons/plugin.video.drnu/resources/lib/tvapi.py", line 79, in read_token
                                                       tokens = json.loads(s)
                                                     File "/usr/lib/python3.9/json/__init__.py", line 346, in loads
                                                       return _default_decoder.decode(s)
                                                     File "/usr/lib/python3.9/json/decoder.py", line 340, in decode
                                                       raise JSONDecodeError("Extra data", s, end)
                                                   json.decoder.JSONDecodeError: Extra data: line 1 column 2523 (char 2522)
                                                   -->End of Python script error report<--
2023-01-25 20:06:56.805 T:922     DEBUG <general>: onExecutionDone(20, /home/osmc/.kodi/addons/plugin.video.drnu/default.py)
2023-01-25 20:06:56.812 T:557     DEBUG <general>: ------ Window Init (DialogNotification.xml) ------
2023-01-25 20:06:56.828 T:922     DEBUG <general>: .
2023-01-25 20:06:56.902 T:922      INFO <general>: Python interpreter stopped
2023-01-25 20:06:56.902 T:922     DEBUG <general>: Thread LanguageInvoker 3592417536 terminating
2023-01-25 20:06:56.921 T:920     ERROR <general>: GetDirectory - Error getting plugin://plugin.video.drnu/
2023-01-25 20:06:56.921 T:920     DEBUG <general>: Thread waiting 3946656000 terminating
2023-01-25 20:06:56.936 T:557     DEBUG <general>: ------ Window Deinit (DialogBusy.xml) ------
2023-01-25 20:06:56.936 T:557     DEBUG <general>: started alarm with name: resetscrollclear1
2023-01-25 20:06:56.937 T:557     DEBUG <general>: started alarm with name: resetscrollclear2
2023-01-25 20:06:56.937 T:557     DEBUG <general>: started alarm with name: resetscrollclear3
2023-01-25 20:06:56.937 T:557     DEBUG <general>: Skipped 1 duplicate messages..
2023-01-25 20:06:56.937 T:557     DEBUG <general>: started alarm with name: resetscrollclear4
2023-01-25 20:06:56.937 T:557     DEBUG <general>: started alarm with name: resetscrollclear5
2023-01-25 20:06:56.938 T:557     DEBUG <general>: started alarm with name: resetscrollclear6
2023-01-25 20:06:56.938 T:557     DEBUG <general>: started alarm with name: resetscrollclear7
2023-01-25 20:06:56.938 T:557     DEBUG <general>: started alarm with name: resetscrollclear8
2023-01-25 20:06:56.938 T:557     DEBUG <general>: started alarm with name: resetscrollclear9
2023-01-25 20:06:56.938 T:557     DEBUG <general>: started alarm with name: resetscrollclear10
2023-01-25 20:06:56.939 T:557     DEBUG <general>: started alarm with name: resetscrollclear11
2023-01-25 20:06:56.939 T:557     DEBUG <general>: started alarm with name: resetscrollclear12
2023-01-25 20:06:56.939 T:557     DEBUG <general>: started alarm with name: resetscrollclear13
2023-01-25 20:06:56.939 T:557     DEBUG <general>: started alarm with name: resetscrollclear14
2023-01-25 20:06:56.939 T:557     DEBUG <general>: started alarm with name: resetscrollclear15
2023-01-25 20:06:56.940 T:557     DEBUG <general>: started alarm with name: resetscrollclear16
2023-01-25 20:06:56.940 T:557     DEBUG <general>: started alarm with name: resetscrollclear17
2023-01-25 20:06:56.940 T:557     DEBUG <general>: started alarm with name: resetscrollclear18
2023-01-25 20:06:56.940 T:557     DEBUG <general>: started alarm with name: resetscrollclear19
2023-01-25 20:06:56.941 T:557     DEBUG <general>: started alarm with name: resetscrollclear20
2023-01-25 20:06:56.941 T:557     DEBUG <general>: started alarm with name: resetscrollclear21
2023-01-25 20:06:56.941 T:557     DEBUG <general>: started alarm with name: resetscrollclear22
2023-01-25 20:06:56.941 T:557     DEBUG <general>: started alarm with name: resetscrollclear23
2023-01-25 20:06:56.941 T:557     DEBUG <general>: started alarm with name: resetscrollclear24
2023-01-25 20:06:56.941 T:557     DEBUG <general>: started alarm with name: resetscrollclear25
2023-01-25 20:06:56.942 T:557     ERROR <general>: CGUIMediaWindow::GetDirectory(plugin://plugin.video.drnu/) failed
2023-01-25 20:06:56.942 T:557     DEBUG <general>: CGUIMediaWindow::GetDirectory (addons://sources/video)
2023-01-25 20:06:56.942 T:557     DEBUG <general>:   ParentPath = []
2023-01-25 20:06:56.943 T:923     DEBUG <general>: Thread waiting start, auto delete: false
2023-01-25 20:06:56.943 T:923     DEBUG <general>: Thread waiting 3946656000 terminating
2023-01-25 20:06:56.946 T:924     DEBUG <general>: Thread BackgroundLoader start, auto delete: false
2023-01-25 20:06:56.949 T:557     DEBUG <general>: [Warning] CGUITextureManager::GetTexturePath: could not find texture 'noop'
2023-01-25 20:06:56.952 T:924     DEBUG <general>: Thread BackgroundLoader 3988226304 terminating
2023-01-25 20:07:02.156 T:557     DEBUG <general>: ------ Window Deinit (DialogNotification.xml) ------`

Versions:
OSMC: January 2023
Kodi: 19.5
DR TV: 6.0.2+matrix.1
Inputstream Adaptive: 19.0.7
Python: 3.9.2

**Comment by TermeHansen** [comment]
Hi Kenneth,

Thank you for the report. I use the addon myself daily on osmc and have never seen this error myself. As a python developer I have seen this before sadly. The json writer in Python can write corrupt json files sometimes, which is what has happened to you.

You need to delete the corrupt 
'/home/osmc/.kodi/userdata/addon_data/plugin.video.drnu/token.json' file.

I will add a check and fallback to the addon for this rare case. I just pushed version 6.1.0 to official kodi, so it will probably first come in a small 6.1.1 release soon after

Let me know if it works, or else we can test a fix together here...

**Comment by ksga** [comment]
> Hi Kenneth,
> 
> Thank you for the report. I use the addon myself daily on osmc and have never seen this error myself. As a python developer I have seen this before sadly. The json writer in Python can write corrupt json files sometimes, which is what has happened to you.
> 
> You need to delete the corrupt '/home/osmc/.kodi/userdata/addon_data/plugin.video.drnu/token.json' file.
> 
> I will add a check and fallback to the addon for this rare case. I just pushed version 6.1.0 to official kodi, so it will probably first come in a small 6.1.1 release soon after
> 
> Let me know if it works, or else we can test a fix together here...

Worked like a charm 😀
Thank you for your support 👍
